name: Title

on:
  pull_request_target:
    types: [opened, edited, reopened]

permissions:
  pull-requests: read

jobs:
  validate_PR_title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
